### ISSUE TITLE
goflow2 + enricher docker

### ISSUE THREAD

**Issue by gmowses** [netsampler/goflow2#115]
I'm using compose ELK and I wanted to add the enricher to the stream, how could I do that?

**Comment by vigodeltoro** [comment]
Hi there.. 
is a message queue an option in front of ELK ? You could write f.e in Kafka in one topic, enrich with a script and write in another topic which is read by ELK ? 

regards

**Comment by lspgn** [comment]
Hello,
You may be able to enrich data with [Elastic](https://www.elastic.co/guide/en/logstash/current/lookup-enrichment.html) or possibly log collection (with [fluentd](https://www.fluentd.org/guides/recipes/apache-add-hostname) in replacement of logstash) but I never tried it.

Otherwise, implementing the enrichment in code before logging.
