### ISSUE TITLE
IPFlags field

### ISSUE THREAD

**Issue by vanyasvl** [netsampler/goflow2#202]
After fixing FragmentOffset field parsing (#190, #196) , we loose any information about IP Flags (DF Don’t Fragment and MF More Fragments)
IP Flags are first 3 bits at data offset+6
I think he have to add new protobuf field IPFlags, like a TCPFlags with IP flags.

**Comment by lspgn** [comment]
After looking a bit more into it (and changes introduced in https://github.com/netsampler/goflow2/issues/184), I also noticed a discrepancy with how I process sFlow vs IPFIX:

https://github.com/netsampler/goflow2/blob/085e34a85f15f79a6a14c5703c6397f3aaa2e61d/producer/proto/producer_nf.go#L489-L494

I'm hesitating reverting the change:

https://github.com/netsampler/goflow2/blob/085e34a85f15f79a6a14c5703c6397f3aaa2e61d/producer/proto/producer_sf.go#L117

in order to avoid having to add an additional protobuf field

**Comment by lspgn** [comment]
In the end I refactored the sFlow parsing and added an extra field for IP flags. Turns out IPv6 fragments offsets aren't at the same position as IPv4 fragments offsets.
