### ISSUE TITLE
Feature: Interface Pretty-Names

### ISSUE THREAD

**Issue by superstes** [netsampler/goflow2#256]
**Is your feature request related to a problem? Please describe.**

I'm using [softflowd](https://github.com/irino/softflowd) to export to goflow2 and use [grafana-agent](https://github.com/grafana/agent)/[grafana-promtail](https://grafana.com/docs/loki/latest/send-data/promtail/stages) to process the data.

To get a basic throughput [metric](https://grafana.com/docs/loki/latest/send-data/promtail/stages/metrics/) we can add-up the flow-bytes per host, if-in and if-out.

That looks like that:

```
flow_throughput{application="netflow_data",flow_if_in="0",flow_if_out="0",flow_vlan_in="0"flow_vlan_out="0",hostname="xxx"} 149368
```

Example [grafana-agent config](https://github.com/shield-wall-net/controller/blob/latest/files/log/grafana-agent.yml#L266)

**Describe the solution you'd like**
What would be very nice to have is an `interface pretty name` instead of the generic interface-id we see.

I would guess that would be easy to implement using the golang [net.Interface](https://pkg.go.dev/net#Interface).

The functionality could be triggered using the `-format.selector` flag.

**Describe alternatives you've considered**
Using rsyslog magic to script it.. but that would not be a very clean approach.

**Comment by superstes** [comment]
Just gave it another thought:
- This (of course) only works if the flow source is localhost
- I'm not sure if that ordering/numbering is 'standardized' and reproducible

**Comment by superstes** [comment]
I've looked into it a little deeper and I am not sure this makes sense in goflow2

Note: I'm pretty new to netflow-related tech. So I do not know much about the standards and so on..

To clarify what i mean:
* It seems the agent I'm using (_softflowd_) does not export the flow-interface-names by default. This is bad as the generic interface-ids that are sent, are not very useful for analyzing the data.
* My thought was that these names could theoretically be added/resolved by goflow2 IF the [SamplerAddress](https://github.com/netsampler/goflow2/blob/main/producer/proto/proto.go#L47) is localhost
   ![NetFlow_IFID_IFName](https://github.com/netsampler/goflow2/assets/50269951/c635a2db-9ff0-452a-9790-42f356fbd67c)

For softflowd there seems also to be the possibility to [enable this functionality at compile-time](https://github.com/irino/softflowd/commit/dcedadb3cd302ddbbcc7fafea98de9b371c4ca69). This does not make me happy, but it gives me an option to work with.

Would GoFlow2 support to receive these?
As far as I understand the [producer_nf.go](https://github.com/netsampler/goflow2/blob/main/producer/proto/producer_nf.go#L341) only processes interface-numbers, yes?

**Comment by lspgn** [comment]
Ah! I understand
So unfortunately, it's too specific to implement such mapping when it's localhost. A lot of GoFlow2 implementations are not on the same machine.

I looked at the [softflowd commit](https://github.com/irino/softflowd/commit/dcedadb3cd302ddbbcc7fafea98de9b371c4ca69) you mentioned. It seems to be adding the [IPFIX field 82](https://www.iana.org/assignments/ipfix/ipfix.xhtml) to the template. GoFlow2 v2 (`main` branch until I cut a release) has custom mappings to decode it:

This said, I'm not sure how the sampler considers it, if it's in OptionTemplates or DataTemplates, is it the source or dest interface, etc.

```yaml
formatter:
  fields: # list of fields to format in JSON
    - ifname
   protobuf: # manual protobuf fields addition
    - name: ifname
      index: 1234
      type: bytes
ipfix:
  mapping:
    - field: 82
      destination: ifname
```

(haven't tested, it may display base64 bytes though since I don't have a string renderer... can look into it)

In a distributed setup: the database stores interface IDs but would also have a [dictionary](https://clickhouse.com/docs/en/sql-reference/dictionaries) to do the mapping at query time.

**Comment by superstes** [comment]
Understandable.
I'll look for other ways.

Thank you for the deeper information.
