### ISSUE TITLE
goflow2 captures IPFIX packets with flow sequenceNum=0, 

### ISSUE THREAD

**Issue by sharmarohit0013** [netsampler/goflow2#26]
HI i tried to use a flow generator https://github.com/sheacloud/flowgen, 
i can see tool is generating IPFIX packets with sequenceNum=0, and goflow2 is parsing these packets. i can see other parsers are not capturing those packets.
not sure if this is valid behaviour
![image](https://user-images.githubusercontent.com/14851167/129491222-66ad6607-5393-428e-a594-a2171d3c53f2.png)

**Comment by lspgn** [comment]
Hello,
Could you share a pcap?

**Comment by lspgn** [comment]
Hello,
When filing an issue please provide more information.
* What are the other parsers?
* Is it causing an issue?
* Can you share a pcap?
* Prefer pasting text instead of sending an image

I am seeing that the original library can set the Sequence ID
https://github.com/vmware/go-ipfix/blob/b66c7039268b657834f475e4a9b5b4d274be5dea/pkg/exporter/process.go#L307 
But I have not checked how flowgen works.

The IPFIX spec indicates
```
   Sequence Number

      Incremental sequence counter modulo 2^32 of all IPFIX Data Records
      sent in the current stream from the current Observation Domain by
      the Exporting Process.  Each SCTP Stream counts sequence numbers
      separately, while all messages in a TCP connection or UDP session
      are considered to be part of the same stream.  This value can be
      used by the Collecting Process to identify whether any IPFIX Data
      Records have been missed.  Template and Options Template Records
      do not increase the Sequence Number.
```
While a constant sequence = 0 is not optimal, it does not imply the packets are to be dropped.
This is valid behavior.
