### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by asas6559** [netsampler/goflow2#280]
Hi，
     I am using goflow2 by docker image，now，i test the performance.
     about 50Kp/s（about 50Mb/s）, goflow2 working fine. but when i increase the pps, it appears some problem.
     onenetflow packets contains one flow info in a packet.
     
**Server configuration**
1. 24 cpus enable hyperthreading,128g memory.
2. Centos 7.2
3. Docker version 24.0.7, build afdd53b
4. core.rmem_max = 91299200
5. Interface configuration: Speed:1000Mb/s，ethtool -g: Current hardware settings:RX:4096.
6. kcg used, goflow version is v2.1.1.
7. 5 tuple contained in payload, all the netflow packets sent by only a netflow exporter.  

**Command start goflow2**
          docker run -d --name goflow2 --network conf_mynet -p 8080:8080 -p 6343:6343/udp -p 2055:2055/udp netsampler/goflow2:v2.1.1 --transport.kafka.brokers=kafka:9092 --transport=kafka --transport.kafka.topic=flows --transport.kafka.hashing=true --format=bin --listen "netflow://:2055/?count=24&workers=48&blocking=false&queue_size=10000000"
     
 **Two questions.**
1. About 100Kp/s（about 100Mb/s）, no packets droped by interface , but goflow2 got less than the packets i sent. i send 10 million packets total, goflow2 show it got 9.98 million packets on 8080/metrics，no dropped packets count show.  Please help analyze where packets may be lost.
2. About 500Kp/s（about 500Mb/s）,  i send 10 million packets total, about 5 million packets droped by interface(i got it by "ethtool -S",and show "rx_missed_errors" count increased about 5 million), but no packets droped by interface when i closed goflow2 and sent the same packets again. Please help analyze the reason and how to fix it.

Thanks!

**Comment by lspgn** [comment]
Hello,

What tool are you using to generate those packets? Is it on the same machine?

What indicates packet drops:

* `flow_dropped_packets_total` on 8080/metrics
* UDP errors from the kernel

Which metric are you using to count the packets? Does it include templates?

In both your questions, did `flow_dropped_packets_total` return anything?

Would you also be able to count the number of packets using the data in Kafka? Possibly counting the sequence number?

Please provide the average CPU and memory usage.
KCG is a nice bootstrap stack but the toolings on the system may use more resources than necessary. Have you tried running just GoFlow2?

In terms of improvements, have you increased/reduced the number of workers?
I think with these amounts of packets, it is advisable to load-balance across multiple machines and scale horizontally: chasing extra packets might not be possible or worth it.

**Comment by asas6559** [comment]
Hi,
I used npb to generate those packets( same packets , goflow2 50Kp/s no problem, the packets is no problem ) , it is directly connected through network cables between npb interface and server interface.  at the beginning, _flow_dropped_packets_total_  appeared, after we increase the count, workers and queue size, flow_dropped_packets_total never appeared again. 

UDP errors from the kernel
----How to get this statistic？is "netstat -su"？

Which metric are you using to count the packets? Does it include templates?
---goflow2_flow_traffic_packets_total

In both your questions, did flow_dropped_packets_total return anything?
---- no

Would you also be able to count the number of packets using the data in Kafka? Possibly counting the sequence number?
----yes ,i count the number in the partition, the records count equals goflow2_flow_traffic_packets_total

Please provide the average CPU and memory usage.
----It seems like the server resources are not fully utilized
![image](https://github.com/netsampler/goflow2/assets/8297696/9cfd416d-2053-41ce-897b-934fedfec888)

I think with these amounts of packets, it is advisable to load-balance across multiple machines and scale horizontally: chasing extra packets might not be possible or worth it.
----the performance.md says  "This software has been tested with hundreds of thousands of flows per second on common hardware",  can goflow2 process 50Kp/s(means 50Kf/s) neflow packets ?

**Comment by lspgn** [comment]
This problem involve many parts that are not _just_ GoFlow2.
I don't think I can help without having control of the environment and the knowledge of these tools and unfortunately I do not have enough time. I would need the exact CLI args used, packet counts observed, resource graphs.

I'm suspecting the tool emitting the flows may also be dropping on the outbound path and are never received. This would have to be tested independently using tcpdumps or sampling locally.
A benchmark will also perform differently than a production environment.
Docker may also play a part as well with the forwarding and NAT-ing. 

>  ----the performance.md says "This software has been tested with hundreds of thousands of flows per second on common hardware", can goflow2 process 50Kp/s(means 50Kf/s) neflow packets ?

In theory yes, and per your specs there should be more capacity available but GoFlow2 can have specific outputs, serializations and other tools running may impact its performance.

The only advice I can give would be to scale horizontally, load-balance the flows (since IPFIX/NetFlow, on a per sampler basis) and dedicate those machines to flow decoding. Kafka and ClickHouse should be setup on other machines.
`htop` and observing the distribution of compute on CPUs will help tuning the buffers and workers count adapted to your environment.
Counting the flow sequence inside ClickHouse using SQL (not just Kafka) will help isolating which packets were dropped.
Comparing with other tools like Akvorado could also provide insights on where the packets are dropped.
