### ISSUE TITLE
Start when kafka is down

### ISSUE THREAD

**Issue by vanyasvl** [netsampler/goflow2#69]
goflow2 works correctly, if loose kafka while already started, but goflow2 can't start if Kafka is down
`level=fatal msg="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"`

Sometimes it happens in real life when server restarts and goflow2 can't start during boot because it can't reach kafka.

Is it possible to ignore it and start despite to unreachable Kafka, and start to produce new messages to Kafka, when Kafka brokers will be online?

**Comment by lspgn** [comment]
Hello,
It is a failure scenario which is useful when deploying (systemd, Kubernetes...) as it is meant to be restarted and rescheduled in the case there is a network issue on the node.
I *think* the Kafka library errors differently since there is a bootstrap step in which the application discovers other brokers and use them as failover, which is why it tries to reconnect. Additionnaly, messages will be retried a few times before giving up.
GoFlow2 does not buffer packets (besides a minimal amount for retries).
It is not possible.
