### ISSUE TITLE
FIRST_SWITCHED and LAST_SWITCH not corresponding RFC or CISCO

### ISSUE THREAD

**Issue by aams-telefonica** [netsampler/goflow2#78]
[RFC 3954](https://datatracker.ietf.org/doc/html/rfc3954) and [NetFlow Version 9 Flow-Record Format](https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html) both specify the fields `FIRST_SWITCHED` and `LAST_SWITCHED` as **System uptime in milliseconds**, however, goflow2 produces them in seconds:
https://github.com/netsampler/goflow2/blob/58f0f97a629cf0cc1d1786c06a27ac2d107717bc/producer/producer_nf.go#L337-L350

Is this an error, or are both fields produced in seconds for a reason I am unaware of?

**Comment by lspgn** [comment]
Hello,
Thank youi for your contribution.
`TimeFlowStart` and `TimeFlowEnd` are in seconds. The reason was at the time it was written, millisecond accuracy was not needed and was inserted nicely in Clickhouse as a DateTime.

I cannot change the unit now as it would break many current implementations.
Furthermore, you are only updating NetFlow v9 and not NetFlow v5 and sFlow.

I hope you understand I cannot merge your PR.
My suggestion would be to introduce `TimeFlowStartMs` and `TimeFlowEndMs` if this new feature receives positive feedbacks.

**Comment by aams-telefonica** [comment]
> My suggestion would be to introduce `TimeFlowStartMs` and `TimeFlowEndMs` if this new feature receives positive feedbacks.

Hello @lspgn,
As other issues has been created (#80) with interest in obtaining the fields `TimeFlowStart` and `TimeFlowEnd` in **milliseconds** for different versions of Netflow. Considering your suggestion I have added the fields `TimeFlowStartMs` and `TimeFlowEndMs` for the versions of Netflow supported by goflow2 (v1, v5 and v10), changes are in the Pull Request #81.
