### ISSUE TITLE
NetFlowStats metric counts flowsets, not flows

### ISSUE THREAD

**Issue by jotak** [netsampler/goflow2#91]
I don't know if it's on purpose or not, the `NetFlowStats` metric counts flow sets: https://github.com/netsampler/goflow2/blob/main/utils/netflow.go#L223-L228
From its name / description, I would assume it should count flows instead:

```go
		prometheus.CounterOpts{
			Name: "flow_process_nf_count",
			Help: "NetFlows processed.",
		},
```

Is it ok to change it so it counts flows? Or should we introduce another metric?

**Comment by lspgn** [comment]
I would prefer introducing another metric in that case. Since we are indicating packets, this could break a lot of user dashboards and trigger alarms if it would increase too much.
Could you do this at the producer level / or in the same section and increment by the number of flow records in the set.

**Comment by jotak** [comment]
Note that there's a workaround to count individual flows: `NetFlowTimeStatsSum` is a histogram for each individual flow, so as part of the histo metrics there's a counter that gets incremented for every call. We can use that instead.
